@ToDoListAPI_HostAddress = https://localhost:7178
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjExIiwiZXhwIjoxNzg0NTI0NDM1LCJpc3MiOiJUb0RvTGlzdEFQSSJ9.wVU-kNxd1Q63lbuwiwSWju5ATdqlDcjYG3qIQqkvsSw 
############################
### AUTH
############################

### 1. LOGIN (POST)
POST {{ToDoListAPI_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "UserName": "",
  "Password": ""
}

############################
### USER
############################

### 1. CREATE USER / REGISTER (POST)
POST {{ToDoListAPI_HostAddress}}/api/user
Content-Type: application/json

{
  "UserName": "",
  "Password": ""
}

### 2. GET MY PROFILE (GET)
GET {{ToDoListAPI_HostAddress}}/api/user
Authorization: Bearer {{token}}
Accept: application/json

### 3. UPDATE MY PROFILE (PUT)
PUT {{ToDoListAPI_HostAddress}}/api/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "UserName": "",
  "OldPassword": "",
  "NewPassword": ""
}

### 4. DELETE MY ACCOUNT (DELETE)
DELETE {{ToDoListAPI_HostAddress}}/api/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Password": ""
}

############################
### TODO
############################

### 1. CREATE TODO (POST)
POST {{ToDoListAPI_HostAddress}}/api/todo
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": ""
}

### 2. GET MY TODOS (GET)
GET {{ToDoListAPI_HostAddress}}/api/todo/user
Authorization: Bearer {{token}}
Accept: application/json

### 3. GET TODO DETAILS (GET)
GET {{ToDoListAPI_HostAddress}}/api/todo/0
Authorization: Bearer {{token}}
Accept: application/json

### 4. UPDATE TODO (PUT)
PUT {{ToDoListAPI_HostAddress}}/api/todo/0
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "todo2",
  "status": 0
}

### 5. DELETE TODO (DELETE)
DELETE {{ToDoListAPI_HostAddress}}/api/todo/0
Authorization: Bearer {{token}}
Accept: application/json

### 6. GET TODOS BY STATUS (GET)
GET {{ToDoListAPI_HostAddress}}/api/todo/status/Pending
Authorization: Bearer {{token}}
Accept: application/json