@ToDoListAPI_HostAddress = http://localhost:5287

Post {{ToDoListAPI_HostAddress}}/api/User
Content-type: application/json

{
  "Username": "testuser2",
  "PasswordHash": "mysecretpassword2"
}

###
GET {{ToDoListAPI_HostAddress}}/api/User
Accept: application/json
